### PR TITLE
Summary, Description and Screenshots for Nextcloud App Store

### PR DESCRIPTION
**Pull request by LukeLR**
I created some simple descriptions and summaries in german and english for the Nextcloud App Store, as well as created a demo database to include some screenshots. I hope I followed the [specification](https://nextcloudappstore.readthedocs.io/en/latest/developer.html#app-metadata) correctly. I wasn't sure if one could include screenshots for different languages though, so here are english screenshots so far. Please review and merge! This adresses issue #59.

### CODE REVIEW

**Comment by LukeLR** [comment]
Previews of the screenshots, for convenience:
[](https://abload.de/image.php?img=bildschirmfotoam2021-kykd8.png) [](https://abload.de/image.php?img=bildschirmfotoam2021-nbk8s.png) [](https://abload.de/image.php?img=bildschirmfotoam2021-u7j37.png) [](https://abload.de/image.php?img=bildschirmfotoam2021-wnjq3.png) [](https://abload.de/image.php?img=bildschirmfotoam2021-m0jq9.png) [](https://abload.de/image.php?img=bildschirmfotoam2021-6dj9p.png) [](https://abload.de/image.php?img=bildschirmfotoam2021-otj7x.png) [](https://abload.de/image.php?img=bildschirmfotoam2021-vuk8t.png) [](https://abload.de/image.php?img=bildschirmfotoam2021-03kxw.png)

**Comment by heitorPB** [comment]
IMO the screenshots should be part of the repository instead of being hosted somewhere else.

**Comment by mtierltd** [comment]
Hi

If you don't mind we would host the images on our own server, so if you are okay with us copying
your files, we would love to take this pull request.

**Comment by DanielRuf** [comment]
> If you don't mind we would host the images on our own server

Just a small reminder. I think this part is still open.

**Pull request merged**
